exclude: [
  "config.rb",
  "Procfile",
  "README",
  "Gemfile",
  "Gemfile.lock",
  "assets/sass",
  "divshot.json",
  "vendor"
]

title     : Jethyo
author    : Rey Dhuny

encoding  : utf-8

port      : 9999

markdown  : kramdown

timezone  : Europe/London
